// =====================================================================
// render_wages_daily.js — Daily Wage Ledger module
// ---------------------------------------------------------------------
// Digitises the EMS "Job Card Summary Report by Job Activity" PDF the
// estate office prints every month: per job activity (JAxxxxx code),
// per job location (block / POLE / OPT…), the normal hours + amount,
// OT hours + amount, and total amount for the period.
//
// The monthly PDF is generated by the payroll system (Intuitive Systems
// EMS) with a real text layer, so it can be imported DIRECTLY — no
// Excel conversion needed. pdf.js (CDN, lazy-loaded) extracts the text
// with x/y coordinates; rows are reconstructed by column position and
// validated against the report's own per-activity totals and grand
// total before anything is saved. An Excel template + import exists as
// a fallback for months where only a spreadsheet is available.
//
// Storage: Firebase  shared/wages_daily_data   (window._wagesDailyDb)
// Surfaced as the "Daily Wage Ledger" sub-tab under 💵 Rate of Wages.
// Access:  menu key 'wages' (shared with the calculator/ledger);
//          template + export available to read-only users.
// =====================================================================

(function () {
    'use strict';

    const WD_MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

    // HTML-escape DB/user free text before innerHTML (shared data → untrusted).
    const wdEsc = (s) => (typeof window.escapeHtml === 'function' ? window.escapeHtml(s) : String(s == null ? '' : s));

    const wdNum = (v) => {
        if (v && typeof v === 'object' && 'result' in v) v = v.result;
        const n = parseFloat(String(v).replace(/,/g, ''));
        return isNaN(n) ? 0 : n;
    };
    const wdText = (v) => {
        if (v && typeof v === 'object') {
            if ('result' in v) v = v.result;
            else if ('text' in v) v = v.text;
            else if (Array.isArray(v.richText)) v = v.richText.map(t => t.text).join('');
        }
        return String(v == null ? '' : v).trim();
    };
    const wdRM = (n) => 'RM' + wdNum(n).toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

    // "645:30" → minutes; also accepts decimal hours ("12.5") and Excel
    // time serials (fraction-of-a-day numbers from a template cell).
    const wdToMin = (v) => {
        if (v == null || v === '') return 0;
        if (typeof v === 'number') return Math.round(v * 24 * 60);      // Excel time serial
        const s = String(v).trim();
        const m = s.match(/^(\d+):([0-5]?\d)$/);
        if (m) return parseInt(m[1]) * 60 + parseInt(m[2]);
        const f = parseFloat(s);
        return isNaN(f) ? 0 : Math.round(f * 60);                        // decimal hours
    };
    const wdFmtMin = (min) => `${Math.floor(min / 60)}:${String(min % 60).padStart(2, '0')}`;

    const wdCurrentYear = () => String(new Date().getFullYear());
    const wdCurrentMonth = () => WD_MONTHS[new Date().getMonth()];

    // ── State helpers ───────────────────────────────────────────────────
    const wdEnsure = () => {
        if (!window.state.wagesDaily) window.state.wagesDaily = {};
        return window.state.wagesDaily;
    };
    const wdGetMonth = (year, month) => {
        const d = wdEnsure();
        return (d[year] && d[year][month]) || null;
    };
    const wdSetMonth = (year, month, obj) => {
        const d = wdEnsure();
        if (!d[year]) d[year] = {};
        d[year][month] = obj;
    };

    const wdYearList = () => {
        const set = new Set();
        [window.state.wagesDaily, window.state.wagesLedger, window.state.wages, window.state.performance]
            .forEach(obj => { if (obj) Object.keys(obj).forEach(k => { if (/^\d{4}$/.test(k)) set.add(k); }); });
        set.add(wdCurrentYear());
        return [...set].sort((a, b) => parseInt(b) - parseInt(a));
    };

    // ── Firebase save ───────────────────────────────────────────────────
    const saveWagesDailyData = (silent) => {
        const db = window._wagesDailyDb || window._wagesDb;
        if (!db) { if (!silent && window.notify) window.notify('Not connected to cloud — not saved.', 'error'); return Promise.resolve(); }
        if (typeof window._markUnsaved === 'function') window._markUnsaved();
        return db.ref('shared/wages_daily_data').set(JSON.stringify(window.state.wagesDaily))
            .then(() => { if (!silent && window.notify) window.notify('Daily wage ledger saved.', 'success'); })
            .catch(e => { if (window.notify) window.notify('Save failed: ' + e.message, 'error'); });
    };
    window.saveWagesDailyData = saveWagesDailyData;

    // ── Lazy CDN loaders ────────────────────────────────────────────────
    const wdEnsureExcelJS = async () => {
        if (typeof window.ExcelJS !== 'undefined') return;
        await new Promise((res, rej) => {
            const s = document.createElement('script');
            s.src = 'https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';
            s.onload = res; s.onerror = () => rej(new Error('Failed to load ExcelJS'));
            document.head.appendChild(s);
        });
    };
    // pdf.js 3.x — last UMD build (4.x is ESM-only, can't be lazy-loaded
    // with a plain <script> tag in this no-build app).
    const WD_PDFJS = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/';
    const wdEnsurePdfJs = async () => {
        if (window.pdfjsLib) return;
        await new Promise((res, rej) => {
            const s = document.createElement('script');
            s.src = WD_PDFJS + 'pdf.min.js';
            s.onload = res; s.onerror = () => rej(new Error('Failed to load pdf.js'));
            document.head.appendChild(s);
        });
        window.pdfjsLib.GlobalWorkerOptions.workerSrc = WD_PDFJS + 'pdf.worker.min.js';
    };

    // =====================================================================
    // PDF import — parse the EMS "Job Card Summary Report by Job Activity"
    // =====================================================================
    // Column x-boundaries in PDF user-space (validated against the real
    // June 2026 report): No. <60 · activity 60–170 · location 170–265 ·
    // the five numeric columns ≥265.
    const X_NO = 60, X_ACT = 170, X_LOC = 265;
    const RE_HOURS = /^\d+:\d{2}$/;
    const RE_MONEY = /^[\d,]+\.\d{2}$/;

    // pdf.js text items are text RUNS — one item may span several words.
    // Split each into words and spread x proportionally by character
    // position so column classification works like word-level extraction.
    const wdItemWords = (item) => {
        const str = item.str;
        const x0 = item.transform[4], y = item.transform[5];
        const w = item.width || 0;
        const out = [];
        const re = /\S+/g;
        let m;
        while ((m = re.exec(str)) !== null) {
            out.push({ text: m[0], x: x0 + (str.length ? (m.index / str.length) * w : 0), y });
        }
        return out;
    };

    const wdParsePdf = async (file) => {
        await wdEnsurePdfJs();
        const buf = await file.arrayBuffer();
        const doc = await window.pdfjsLib.getDocument({ data: buf }).promise;

        const activities = [];
        let cur = null, grand = null, period = null;
        let looksRight = false;
        const close = () => { if (cur) { activities.push(cur); cur = null; } };

        for (let p = 1; p <= doc.numPages; p++) {
            const page = await doc.getPage(p);
            const content = await page.getTextContent();
            let words = [];
            content.items.forEach(it => { if (it.str && it.str.trim()) words = words.concat(wdItemWords(it)); });

            // Group into lines by y (pdf.js y is bottom-up → sort DESC).
            // Sub-rows of one visual line sit ≤2pt apart; real rows ~35pt.
            words.sort((a, b) => b.y - a.y || a.x - b.x);
            const lines = [];
            words.forEach(wd => {
                const last = lines[lines.length - 1];
                if (last && Math.abs(wd.y - last.y) <= 3) last.words.push(wd);
                else lines.push({ y: wd.y, words: [wd] });
            });

            for (const line of lines) {
                line.words.sort((a, b) => a.x - b.x);
                const text = line.words.map(w => w.text).join(' ');

                if (/Job Card Summary Report/i.test(text)) { looksRight = true; continue; }
                if (/Registration No\.|\(PRINTED|Copyright|Generated By|Search Criteria|^Job Date|^Page \d+ of|^generation$/i.test(text)) continue;
                const pm = text.match(/From (\d{2})\/(\d{2})\/(\d{4}) To (\d{2})\/(\d{2})\/(\d{4})/);
                if (pm) { period = { from: `${pm[3]}-${pm[2]}-${pm[1]}`, to: `${pm[6]}-${pm[5]}-${pm[4]}` }; continue; }
                if (/Job Location/.test(text) || /^Total Normal/.test(text)) continue;

                const numToks = line.words.filter(w => w.x >= X_LOC && (RE_HOURS.test(w.text) || RE_MONEY.test(w.text)));
                const actToks = line.words.filter(w => w.x >= X_NO && w.x < X_ACT && !numToks.includes(w));
                const locToks = line.words.filter(w => w.x >= X_ACT && w.x < X_LOC && !numToks.includes(w));
                const noToks = line.words.filter(w => w.x < X_NO);
                const locText = locToks.map(w => w.text).join(' ');

                if (/^Grand Total/.test(text) && numToks.length === 5) {
                    grand = numToks.map(w => w.text);
                    continue;
                }
                if (noToks.length && /^\d+$/.test(noToks[0].text)) {
                    close();
                    cur = { no: parseInt(noToks[0].text), nameParts: [], rows: [], total: null };
                }
                if (actToks.length && cur) cur.nameParts.push(...actToks.map(w => w.text));
                if (numToks.length === 5 && cur) {
                    const v = numToks.map(w => w.text);
                    if (locText === 'Total') cur.total = v;
                    else if (locText) cur.rows.push({
                        location: locText,
                        normalHours: v[0], normalAmount: wdNum(v[1]),
                        otHours: v[2], otAmount: wdNum(v[3]),
                        totalAmount: wdNum(v[4]),
                    });
                }
            }
        }
        close();

        if (!looksRight || !activities.length) {
            throw new Error('This does not look like a "Job Card Summary Report by Job Activity" PDF (no recognisable rows found). If it is a scanned copy, convert it to Excel and use 📥 Import Excel instead.');
        }

        // Activity code/name: first token is the JA code; drop only the
        // separator dash straight after it (names may contain their own "-").
        const out = activities.map(a => {
            const parts = a.nameParts.slice();
            const code = parts.shift() || '';
            if (parts[0] === '-') parts.shift();
            return { no: a.no, code, name: parts.join(' '), rows: a.rows, _total: a.total };
        });

        // Validate every per-activity total + the grand total against the
        // summed rows — a parse slip must never be silently saved.
        const issues = [];
        let gnh = 0, gna = 0, goh = 0, goa = 0, gta = 0;
        out.forEach(a => {
            const nh = a.rows.reduce((s, r) => s + wdToMin(r.normalHours), 0);
            const na = a.rows.reduce((s, r) => s + r.normalAmount, 0);
            const oh = a.rows.reduce((s, r) => s + wdToMin(r.otHours), 0);
            const oa = a.rows.reduce((s, r) => s + r.otAmount, 0);
            const ta = a.rows.reduce((s, r) => s + r.totalAmount, 0);
            gnh += nh; gna += na; goh += oh; goa += oa; gta += ta;
            const t = a._total;
            if (t && (nh !== wdToMin(t[0]) || Math.abs(na - wdNum(t[1])) > 0.011 ||
                      oh !== wdToMin(t[2]) || Math.abs(oa - wdNum(t[3])) > 0.011 ||
                      Math.abs(ta - wdNum(t[4])) > 0.011)) {
                issues.push(`${a.code}: rows sum to ${wdRM(ta)} but the report subtotal is ${wdRM(wdNum(t[4]))}`);
            }
            delete a._total;
        });
        if (grand && Math.abs(gta - wdNum(grand[4])) > 0.011) {
            issues.push(`Grand total: rows sum to ${wdRM(gta)} but the report says ${wdRM(wdNum(grand[4]))}`);
        }

        return { activities: out, period, issues, totals: { gnh, gna, goh, goa, gta } };
    };

    // =====================================================================
    // Excel import (fallback) — flat sheet, one row per activity+location
    // =====================================================================
    const WD_COLS = [
        { key: 'no', header: 'No.', w: 6 },
        { key: 'code', header: 'Job Activity Code', w: 16 },
        { key: 'name', header: 'Job Activity Name', w: 42 },
        { key: 'location', header: 'Job Location', w: 14 },
        { key: 'normalHours', header: 'Normal Hours (HH:MM)', w: 18 },
        { key: 'normalAmount', header: 'Normal Amount (RM)', w: 17 },
        { key: 'otHours', header: 'OT Hours (HH:MM)', w: 15 },
        { key: 'otAmount', header: 'OT Amount (RM)', w: 14 },
        { key: 'totalAmount', header: 'Total Amount (RM)', w: 16 },
    ];
    const wdNormHeader = (h) => wdText(h).toUpperCase().replace(/[^A-Z0-9]/g, '');
    const WD_FIELD_MAP = {};
    WD_COLS.forEach(c => { WD_FIELD_MAP[wdNormHeader(c.header)] = c.key; });
    // tolerate simpler headers too
    Object.assign(WD_FIELD_MAP, {
        'NO': 'no', 'CODE': 'code', 'JOBACTIVITY': 'name', 'ACTIVITY': 'name',
        'LOCATION': 'location', 'BLOCK': 'location',
        'NORMALHOURS': 'normalHours', 'NORMALAMOUNT': 'normalAmount',
        'OTHOURS': 'otHours', 'OTAMOUNT': 'otAmount', 'TOTALAMOUNT': 'totalAmount', 'TOTAL': 'totalAmount',
    });

    const wdParseExcel = async (file) => {
        await wdEnsureExcelJS();
        const wb = new window.ExcelJS.Workbook();
        await wb.xlsx.load(await file.arrayBuffer());

        let rows = null;
        wb.eachSheet(ws => {
            if (rows) return;
            // find the header row by signature
            let hdrIdx = 0, colMap = null;
            ws.eachRow((row, idx) => {
                if (colMap) return;
                const toks = (row.values || []).map(wdNormHeader);
                if (toks.includes('JOBACTIVITYCODE') || (toks.includes('JOBLOCATION') && (toks.includes('NORMALHOURSHHMM') || toks.includes('NORMALHOURS')))) {
                    hdrIdx = idx; colMap = {};
                    toks.forEach((t, c) => { const f = WD_FIELD_MAP[t]; if (f && colMap[f] === undefined) colMap[f] = c; });
                }
            });
            if (!colMap) return;
            const out = [];
            ws.eachRow((row, idx) => {
                if (idx <= hdrIdx) return;
                const vals = row.values || [];
                const get = (f) => (colMap[f] === undefined ? '' : vals[colMap[f]]);
                const code = wdText(get('code'));
                const location = wdText(get('location'));
                if (!code && !location) return;                       // blank / stray row
                if (/^(GRAND\s*)?TOTAL$/i.test(location) || /^(GRAND\s*)?TOTAL$/i.test(code)) return; // totals recomputed
                const na = wdNum(get('normalAmount')), oa = wdNum(get('otAmount'));
                let ta = wdNum(get('totalAmount'));
                if (!ta) ta = +(na + oa).toFixed(2);
                // hours cells may be strings ("645:30"), Excel time serials,
                // or ExcelJS formula objects ({ result }) — unwrap first
                const hoursVal = (f) => {
                    let v = get(f);
                    if (v && typeof v === 'object' && 'result' in v) v = v.result;
                    return typeof v === 'number' ? v : wdText(v);
                };
                out.push({
                    no: wdNum(get('no')) || '',
                    code, name: wdText(get('name')), location,
                    normalHours: wdFmtMin(wdToMin(hoursVal('normalHours'))),
                    normalAmount: na,
                    otHours: wdFmtMin(wdToMin(hoursVal('otHours'))),
                    otAmount: oa, totalAmount: ta,
                });
            });
            if (out.length) rows = out;
        });
        if (!rows) throw new Error('No recognisable sheet found — expected columns like "Job Activity Code", "Job Location", "Normal Hours".');

        // group flat rows into activities, keeping first-seen order
        const byCode = new Map();
        rows.forEach(r => {
            if (!byCode.has(r.code)) byCode.set(r.code, { no: byCode.size + 1, code: r.code, name: r.name, rows: [] });
            const a = byCode.get(r.code);
            if (!a.name && r.name) a.name = r.name;
            a.rows.push({ location: r.location, normalHours: r.normalHours, normalAmount: r.normalAmount, otHours: r.otHours, otAmount: r.otAmount, totalAmount: r.totalAmount });
        });
        return { activities: [...byCode.values()], period: null, issues: [] };
    };

    // ── Shared import entry (PDF or Excel decided by extension) ─────────
    const importWagesDaily = async (file, year, month) => {
        if (!file) return;
        if (typeof window._canEdit === 'function' && !window._canEdit('wages')) {
            if (window.notify) window.notify('You do not have edit access for wages.', 'warn');
            return;
        }
        try {
            const isPdf = /\.pdf$/i.test(file.name);
            const parsed = isPdf ? await wdParsePdf(file) : await wdParseExcel(file);
            const nRows = parsed.activities.reduce((s, a) => s + a.rows.length, 0);
            const grand = parsed.activities.reduce((s, a) => s + a.rows.reduce((t, r) => t + r.totalAmount, 0), 0);

            let msg = `Import into ${month} ${year}:\n\n• ${parsed.activities.length} job activities, ${nRows} location rows\n• Grand total ${wdRM(grand)}`;
            if (parsed.period) msg += `\n• Report period ${parsed.period.from} → ${parsed.period.to}`;
            if (parsed.issues.length) msg += `\n\n⚠ CHECK — totals did not fully reconcile:\n${parsed.issues.join('\n')}`;
            if (wdGetMonth(year, month)) msg += `\n\n⚠ This REPLACES the existing ${month} ${year} data.`;
            if (!confirm(msg + '\n\nProceed?')) return;

            wdSetMonth(year, month, {
                periodFrom: parsed.period ? parsed.period.from : '',
                periodTo: parsed.period ? parsed.period.to : '',
                activities: parsed.activities,
                importedAt: new Date().toISOString(),
                importedBy: window.currentUserEmail || (window.auth && window.auth.currentUser && window.auth.currentUser.email) || 'import',
                sourceFile: file.name,
            });
            await saveWagesDailyData(false);
            if (typeof window.logAudit === 'function') window.logAudit('import', 'wages_daily', `${month} ${year}: ${parsed.activities.length} activities / ${nRows} rows (${isPdf ? 'PDF' : 'Excel'})`, year);
            window.renderWagesDailyView();
            if (window.notify) window.notify(`Imported ${nRows} row(s) into ${month} ${year}.`, 'success');
        } catch (err) {
            console.error('Daily wage ledger import error:', err);
            if (window.notify) window.notify('Import error: ' + err.message, 'error');
        }
    };
    window.importWagesDaily = importWagesDaily;

    // =====================================================================
    // Template download — flat importable sheet
    // =====================================================================
    const downloadWagesDailyTemplate = async (year, month) => {
        await wdEnsureExcelJS();
        const wb = new window.ExcelJS.Workbook();
        const ws = wb.addWorksheet('Daily Wage Ledger');
        ws.getCell('A1').value = `Daily Wage Ledger — ${month} ${year}`;
        ws.getCell('A1').font = { bold: true, size: 14 };
        ws.getCell('A2').value = 'One row per job activity + location. Repeat the activity code/name on every row. Hours as text "645:30". Total Amount is auto-computed on import if left blank.';
        ws.getCell('A2').font = { italic: true, size: 9, color: { argb: 'FF666666' } };

        const HR = 4;
        const hdr = ws.getRow(HR);
        hdr.values = WD_COLS.map(c => c.header);
        hdr.height = 28;
        const border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
        hdr.eachCell(cell => {
            cell.font = { bold: true, color: { argb: 'FFF8FAFC' } };
            cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF166534' } };
            cell.border = border;
        });
        WD_COLS.forEach((c, i) => { ws.getColumn(i + 1).width = c.w; });
        // example row
        const ex = ws.getRow(HR + 1);
        ex.values = [1, 'JA02006', 'CIRCLE & PATH SLASHING', '027-15', '3075:00', 15661.10, '0:00', 0, 15661.10];
        ex.font = { italic: true, color: { argb: 'FF999999' } };
        for (let r = HR + 1; r <= HR + 300; r++) {
            const row = ws.getRow(r);
            [5, 7].forEach(c => { row.getCell(c).numFmt = '@'; });        // hours stay text
            [6, 8, 9].forEach(c => { row.getCell(c).numFmt = '#,##0.00'; });
        }
        ws.views = [{ state: 'frozen', ySplit: HR }];

        const buf = await wb.xlsx.writeBuffer();
        const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `Daily_Wage_Ledger_Template_${month}_${year}.xlsx`;
        document.body.appendChild(a); a.click();
        setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 1000);
        if (window.notify) window.notify('Template downloaded.', 'success');
    };
    window.downloadWagesDailyTemplate = downloadWagesDailyTemplate;

    // =====================================================================
    // Excel export — mirrors the on-screen grouped table
    // =====================================================================
    const downloadWagesDailyReport = async (year, month) => {
        const m = wdGetMonth(year, month);
        if (!m || !m.activities || !m.activities.length) {
            if (window.notify) window.notify(`No daily wage data for ${month} ${year}.`, 'warn');
            return;
        }
        await wdEnsureExcelJS();
        const wb = new window.ExcelJS.Workbook();
        const ws = wb.addWorksheet(`Daily Wages ${month} ${year}`);
        ws.getCell('A1').value = `Daily Wage Ledger — ${month} ${year}`;
        ws.getCell('A1').font = { bold: true, size: 14 };
        if (m.periodFrom) {
            ws.getCell('A2').value = `Period ${m.periodFrom} to ${m.periodTo}`;
            ws.getCell('A2').font = { size: 9, color: { argb: 'FF666666' } };
        }
        let r = 4;
        const hdr = ws.getRow(r++);
        hdr.values = WD_COLS.map(c => c.header);
        hdr.font = { bold: true };
        hdr.border = { bottom: { style: 'medium' } };
        WD_COLS.forEach((c, i) => { ws.getColumn(i + 1).width = c.w; });

        let gnh = 0, gna = 0, goh = 0, goa = 0, gta = 0;
        m.activities.forEach(a => {
            let nh = 0, na = 0, oh = 0, oa = 0, ta = 0;
            a.rows.forEach(rw => {
                ws.getRow(r++).values = [a.no, a.code, a.name, rw.location, rw.normalHours, rw.normalAmount, rw.otHours, rw.otAmount, rw.totalAmount];
                nh += wdToMin(rw.normalHours); na += rw.normalAmount;
                oh += wdToMin(rw.otHours); oa += rw.otAmount; ta += rw.totalAmount;
            });
            const tr = ws.getRow(r++);
            tr.values = ['', '', '', 'Total', wdFmtMin(nh), +na.toFixed(2), wdFmtMin(oh), +oa.toFixed(2), +ta.toFixed(2)];
            tr.font = { bold: true };
            tr.border = { top: { style: 'thin' } };
            gnh += nh; gna += na; goh += oh; goa += oa; gta += ta;
        });
        const gr = ws.getRow(r++);
        gr.values = ['', '', '', 'Grand Total', wdFmtMin(gnh), +gna.toFixed(2), wdFmtMin(goh), +goa.toFixed(2), +gta.toFixed(2)];
        gr.font = { bold: true, size: 12 };
        gr.border = { top: { style: 'double' } };
        for (let rr = 5; rr < r; rr++) [6, 8, 9].forEach(c => { ws.getRow(rr).getCell(c).numFmt = '#,##0.00'; });

        const buf = await wb.xlsx.writeBuffer();
        const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `Daily_Wage_Ledger_${month}_${year}.xlsx`;
        document.body.appendChild(a); a.click();
        setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 1000);
        if (window.notify) window.notify('Report downloaded.', 'success');
    };
    window.downloadWagesDailyReport = downloadWagesDailyReport;

    // =====================================================================
    // Main render
    // =====================================================================
    const SS = 'padding:0.45rem 0.6rem;border:1px solid var(--border-color,#ccc);border-radius:4px;background:var(--bg-card,#fff);color:var(--text-primary);font-size:0.9rem;';
    const CARD = 'border:1px solid var(--border-color,#ddd);border-radius:8px;padding:1.1rem 1.25rem;margin-bottom:1rem;background:var(--bg-card,#fff);box-shadow:0 1px 3px rgba(0,0,0,0.05);';
    const BTN = 'padding:0.45rem 1rem;border:1px solid var(--border-color,#ccc);border-radius:4px;background:var(--bg-card,#fff);color:var(--text-primary);cursor:pointer;';

    let _wdFilter = '';   // activity/location contains-filter (session only)

    window.renderWagesDailyView = () => {
        const host = document.getElementById('wages-daily-wrapper');
        if (!host) return;

        const state = window.state;
        if (!state.wagesDailyYear || !/^\d{4}$/.test(state.wagesDailyYear)) state.wagesDailyYear = wdCurrentYear();
        if (!state.wagesDailyMonth || !WD_MONTHS.includes(state.wagesDailyMonth)) state.wagesDailyMonth = wdCurrentMonth();
        const year = state.wagesDailyYear, month = state.wagesDailyMonth;
        const canEdit = (typeof window._canEdit !== 'function') || window._canEdit('wages');

        const yearOpts = wdYearList().map(y => `<option value="${y}" ${y === year ? 'selected' : ''}>${y}</option>`).join('');
        const monthOpts = WD_MONTHS.map(mm => `<option value="${mm}" ${mm === month ? 'selected' : ''}>${mm}</option>`).join('');

        host.innerHTML = `
        <div style="padding:1.25rem 1.5rem; max-width:1300px;">
          <h2 style="margin:0 0 0.25rem; color:var(--text-primary);">📆 Daily Wage Ledger</h2>
          <p style="color:var(--text-secondary); margin:0 0 1.1rem; font-size:0.85rem;">
            The monthly <em>Job Card Summary Report by Job Activity</em> — normal &amp; OT hours and amounts per
            job activity and location. <strong>Import the payroll PDF directly</strong> (rows are validated against
            the report's own totals), or use the Excel template as a fallback.
          </p>

          <div style="display:flex; gap:0.6rem; flex-wrap:wrap; align-items:center; margin-bottom:1.1rem;">
            <label style="font-size:0.82rem; color:var(--text-secondary);">Year
              <select id="wd-year" style="${SS} margin-left:4px;">${yearOpts}</select></label>
            <label style="font-size:0.82rem; color:var(--text-secondary);">Month
              <select id="wd-month" style="${SS} margin-left:4px;">${monthOpts}</select></label>
            <div style="flex:1;"></div>
            <button id="wd-dl-template" style="${BTN}" title="Download a blank Excel import template">⬇ Template</button>
            <button id="wd-dl-report" style="${BTN}" title="Export this month to Excel">📤 Export</button>
            <button id="wd-import-pdf" class="btn-primary" style="padding:0.45rem 1rem; ${canEdit ? '' : 'opacity:.5; cursor:not-allowed;'}" ${canEdit ? '' : 'disabled'} title="${canEdit ? 'Import the payroll Job Card Summary PDF' : 'You do not have edit access for wages'}">📄 Import PDF</button>
            <button id="wd-import-xlsx" style="${BTN} ${canEdit ? '' : 'opacity:.5; cursor:not-allowed;'}" ${canEdit ? '' : 'disabled'} title="${canEdit ? 'Import a filled Excel template' : 'You do not have edit access for wages'}">📥 Import Excel</button>
            <input type="file" id="wd-pdf-input" accept=".pdf" style="display:none;">
            <input type="file" id="wd-xlsx-input" accept=".xlsx,.xls" style="display:none;">
          </div>

          <div id="wd-body"></div>
        </div>`;

        host.querySelector('#wd-year').onchange = (e) => { state.wagesDailyYear = e.target.value; _wdFilter = ''; window.renderWagesDailyView(); };
        host.querySelector('#wd-month').onchange = (e) => { state.wagesDailyMonth = e.target.value; _wdFilter = ''; window.renderWagesDailyView(); };

        // Prev/next month arrows beside the Month selector
        if (typeof window.makeMonthArrowEls === 'function' && typeof window.stepMonthAcross === 'function') {
            const mSel = host.querySelector('#wd-month');
            const mLabel = mSel ? mSel.closest('label') : null;
            if (mLabel) {
                const years = wdYearList();
                const goto = (delta) => {
                    const next = window.stepMonthAcross(year, month, WD_MONTHS, years, delta);
                    if (!next) return;
                    state.wagesDailyYear = next.year; state.wagesDailyMonth = next.month;
                    _wdFilter = ''; window.renderWagesDailyView();
                };
                const a = window.makeMonthArrowEls(
                    !!window.stepMonthAcross(year, month, WD_MONTHS, years, -1),
                    !!window.stepMonthAcross(year, month, WD_MONTHS, years, 1),
                    () => goto(-1), () => goto(1), { height: '32px' });
                const wrap = document.createElement('span');
                wrap.style.cssText = 'display:inline-flex; align-items:center; gap:0.35rem; margin-left:2px;';
                wrap.appendChild(a.prevBtn); wrap.appendChild(a.nextBtn);
                mLabel.insertAdjacentElement('afterend', wrap);
            }
        }

        const busy = async (id, fn) => {
            const btn = host.querySelector(id);
            btn.disabled = true; const old = btn.textContent; btn.textContent = '⏳ …';
            try { await fn(); }
            catch (err) { if (window.notify) window.notify(err.message, 'error'); }
            finally { btn.disabled = false; btn.textContent = old; }
        };
        host.querySelector('#wd-dl-template').onclick = () => busy('#wd-dl-template', () => downloadWagesDailyTemplate(year, month));
        host.querySelector('#wd-dl-report').onclick = () => busy('#wd-dl-report', () => downloadWagesDailyReport(year, month));

        if (canEdit) {
            const pdfIn = host.querySelector('#wd-pdf-input');
            const xlsIn = host.querySelector('#wd-xlsx-input');
            host.querySelector('#wd-import-pdf').onclick = () => pdfIn.click();
            host.querySelector('#wd-import-xlsx').onclick = () => xlsIn.click();
            pdfIn.onchange = async () => { const f = pdfIn.files[0]; pdfIn.value = ''; if (f) await busy('#wd-import-pdf', () => importWagesDaily(f, year, month)); };
            xlsIn.onchange = async () => { const f = xlsIn.files[0]; xlsIn.value = ''; if (f) await busy('#wd-import-xlsx', () => importWagesDaily(f, year, month)); };
        }

        wdRenderBody(year, month);
    };

    const wdRenderBody = (year, month) => {
        const body = document.getElementById('wd-body');
        if (!body) return;
        const m = wdGetMonth(year, month);

        if (!m || !m.activities || !m.activities.length) {
            body.innerHTML = `<div style="${CARD} text-align:center; color:var(--text-secondary);">
                No daily wage data for <strong>${wdEsc(month)} ${wdEsc(year)}</strong> yet.<br><br>
                Click <strong>📄 Import PDF</strong> and pick the month's <em>Job Card Summary Report</em> straight from payroll —
                or <strong>⬇ Template</strong> / <strong>📥 Import Excel</strong> if you only have a spreadsheet.
            </div>`;
            return;
        }

        // ── Totals ──
        let gnh = 0, gna = 0, goh = 0, goa = 0, gta = 0;
        const locTotals = {};
        m.activities.forEach(a => a.rows.forEach(r => {
            gnh += wdToMin(r.normalHours); gna += r.normalAmount;
            goh += wdToMin(r.otHours); goa += r.otAmount; gta += r.totalAmount;
            const L = r.location || '(none)';
            locTotals[L] = (locTotals[L] || 0) + r.totalAmount;
        }));

        const locRows = Object.entries(locTotals).sort((a, b) => b[1] - a[1])
            .map(([L, v]) => `<tr><td style="padding:3px 8px;">${wdEsc(L)}</td><td style="padding:3px 8px; text-align:right;">${wdRM(v)}</td></tr>`).join('');

        const meta = [];
        if (m.periodFrom) meta.push(`period ${wdEsc(m.periodFrom)} → ${wdEsc(m.periodTo)}`);
        if (m.sourceFile) meta.push(`from <em>${wdEsc(m.sourceFile)}</em>`);
        if (m.importedAt) meta.push(`imported ${wdEsc(String(m.importedAt).slice(0, 10))}`);

        const summary = `
        <div style="${CARD} background:var(--bg-main,#f7f9f7); border:2px solid var(--accent-color,#16a34a);">
          <h3 style="margin:0 0 0.2rem; font-size:1rem; color:var(--text-primary);">Summary — ${wdEsc(month)} ${wdEsc(year)}</h3>
          ${meta.length ? `<div style="font-size:0.76rem; color:var(--text-secondary); margin-bottom:0.7rem;">${meta.join(' · ')}</div>` : ''}
          <div style="display:flex; gap:2rem; flex-wrap:wrap; align-items:flex-start;">
            <table style="border-collapse:collapse; font-size:0.9rem; color:var(--text-primary); min-width:300px;">
              <tr><td style="padding:4px 0;">Normal — ${wdFmtMin(gnh)} hrs</td><td style="text-align:right; padding:4px 0 4px 1.5rem;">${wdRM(gna)}</td></tr>
              <tr><td style="padding:4px 0;">Overtime — ${wdFmtMin(goh)} hrs</td><td style="text-align:right; padding:4px 0 4px 1.5rem;">${wdRM(goa)}</td></tr>
              <tr style="border-top:2px solid var(--border-color,#ccc); font-weight:700; font-size:1.05rem;">
                <td style="padding:8px 0;">Grand total <span style="font-weight:400; color:var(--text-secondary); font-size:0.8rem;">(${m.activities.length} activities)</span></td>
                <td style="text-align:right; padding:8px 0;">${wdRM(gta)}</td></tr>
            </table>
            <div style="flex:1; min-width:260px;">
              <div style="font-size:0.82rem; color:var(--text-secondary); margin-bottom:4px;">Per location (all activities)</div>
              <div style="max-height:220px; overflow:auto; border:1px solid var(--border-color,#e3e3e3); border-radius:6px;">
                <table style="width:100%; border-collapse:collapse; font-size:0.85rem; color:var(--text-primary);">${locRows}</table>
              </div>
            </div>
          </div>
        </div>`;

        // ── Grouped table ──
        const f = _wdFilter.toLowerCase().trim();
        const TH = 'padding:6px 8px; border-bottom:2px solid var(--border-color,#ccc); position:sticky; top:0; background:var(--bg-card,#fff); z-index:1; white-space:nowrap;';
        const TD = 'padding:4px 8px; border-bottom:1px solid var(--border-color,#eee); white-space:nowrap;';
        let rowsHtml = '';
        m.activities.forEach(a => {
            const matchAct = !f || (a.code + ' ' + a.name).toLowerCase().includes(f);
            const rows = matchAct ? a.rows : a.rows.filter(r => (r.location || '').toLowerCase().includes(f));
            if (!rows.length) return;
            rowsHtml += `<tr style="background:var(--bg-main,#eef4ee);">
                <td colspan="7" style="${TD} font-weight:700;">${a.no ? wdEsc(String(a.no)) + '.' : ''} ${wdEsc(a.code)} — ${wdEsc(a.name)}</td></tr>`;
            let nh = 0, na = 0, oh = 0, oa = 0, ta = 0;
            rows.forEach(r => {
                nh += wdToMin(r.normalHours); na += r.normalAmount;
                oh += wdToMin(r.otHours); oa += r.otAmount; ta += r.totalAmount;
                rowsHtml += `<tr>
                    <td style="${TD}"></td>
                    <td style="${TD}">${wdEsc(r.location)}</td>
                    <td style="${TD} text-align:right;">${wdEsc(r.normalHours)}</td>
                    <td style="${TD} text-align:right;">${wdNum(r.normalAmount).toLocaleString('en-MY', { minimumFractionDigits: 2 })}</td>
                    <td style="${TD} text-align:right;">${wdEsc(r.otHours)}</td>
                    <td style="${TD} text-align:right;">${wdNum(r.otAmount).toLocaleString('en-MY', { minimumFractionDigits: 2 })}</td>
                    <td style="${TD} text-align:right; font-weight:600;">${wdNum(r.totalAmount).toLocaleString('en-MY', { minimumFractionDigits: 2 })}</td></tr>`;
            });
            rowsHtml += `<tr style="font-weight:700; border-top:1px solid var(--border-color,#ccc);">
                <td style="${TD}"></td><td style="${TD}">Total</td>
                <td style="${TD} text-align:right;">${wdFmtMin(nh)}</td>
                <td style="${TD} text-align:right;">${na.toLocaleString('en-MY', { minimumFractionDigits: 2 })}</td>
                <td style="${TD} text-align:right;">${wdFmtMin(oh)}</td>
                <td style="${TD} text-align:right;">${oa.toLocaleString('en-MY', { minimumFractionDigits: 2 })}</td>
                <td style="${TD} text-align:right;">${ta.toLocaleString('en-MY', { minimumFractionDigits: 2 })}</td></tr>`;
        });
        if (!rowsHtml) rowsHtml = `<tr><td colspan="7" style="padding:16px; text-align:center; color:var(--text-secondary);">No activities or locations match "${wdEsc(_wdFilter)}".</td></tr>`;

        body.innerHTML = summary + `
        <div style="${CARD} padding:0; overflow:hidden;">
          <div style="display:flex; align-items:center; gap:10px; padding:0.8rem 1.1rem; background:var(--bg-main,#f3f5f3); border-bottom:1px solid var(--border-color,#e0e0e0);">
            <h3 style="margin:0; font-size:0.98rem; color:var(--text-primary); flex:1;">By job activity</h3>
            <input type="text" id="wd-filter" value="${wdEsc(_wdFilter)}" placeholder="🔎 filter activity / location" style="${SS} font-size:0.8rem; width:220px;">
          </div>
          <div style="max-height:560px; overflow:auto;">
            <table style="width:100%; border-collapse:collapse; font-size:0.84rem; color:var(--text-primary);">
              <thead><tr>
                <th style="${TH} width:30px;"></th>
                <th style="${TH} text-align:left;">Location</th>
                <th style="${TH} text-align:right;">Normal Hrs</th>
                <th style="${TH} text-align:right;">Normal RM</th>
                <th style="${TH} text-align:right;">OT Hrs</th>
                <th style="${TH} text-align:right;">OT RM</th>
                <th style="${TH} text-align:right;">Total RM</th>
              </tr></thead>
              <tbody>${rowsHtml}</tbody>
            </table>
          </div>
        </div>`;

        const filterInput = body.querySelector('#wd-filter');
        if (filterInput) {
            filterInput.oninput = () => {
                _wdFilter = filterInput.value;
                // re-render only the body; restore filter focus/caret
                const pos = filterInput.selectionStart;
                wdRenderBody(year, month);
                const again = document.getElementById('wd-filter');
                if (again) { again.focus(); again.setSelectionRange(pos, pos); }
            };
        }
    };

})();
